name: shunkworks-dev
channels:
  - conda-forge
dependencies:
  - gufe
  - openfe
  - mdtraj
  - numpy
  - openmm
  - openmmtools
  - openmmforcefields
  - openff-models
  - openff-units
  - openff-toolkit
